Repository ansible-community/toolset, pull requests merged in 2020-11, with the labels that each got.

#4 Rename project to toolset
  Makefile
  README.md
Labels: enhancement

#5 Implement requirements pinning
  .github/workflows/tox.yml
  Dockerfile
  Makefile
  requirements.in
  requirements.txt
  tox.ini
Labels: enhancement

#8 Enable pre-commit
  .github/workflows/container-image.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .yamllint
  tox.ini
Labels: enhancement

#9 Dropped use of py3 system packages
  Dockerfile
Labels: enhancement

#11 Disabled annotations in deps lock file
  requirements.txt
  tox.ini
Labels: bug

#12 Improve container building
  Makefile
  tox.ini
Labels: enhancement

#15 Improved container
  Dockerfile
  Makefile
  README.md
Labels: enhancement

#16 Use mirrored base image
  Dockerfile
  tools/mirror-base-image
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#26 Improve use of apt in Dockerfile
  Dockerfile
Labels: enhancement

#25 Fix docker debian package
  Dockerfile
Labels: bug

#23 Add podman to the container
  Dockerfile
Labels: enhancement

#27 Enable ANSI colors
  Dockerfile
Labels: bug
