Repository ansible-community/toolset, pull requests merged in 2021-03, with the labels that each got.

#114 Updated deps
  requirements.txt
Labels: dependencies

#113 Assure git is present inside container
  Dockerfile
Labels: bug

#119 Dependencies update
  requirements.txt
Labels: enhancement

#115 feat: Add ssh into docker container
  Dockerfile
Labels: enhancement

#111 Use bash as a default command
  Dockerfile
  README.md
Labels: enhancement

#123 Add back yamllint as dependency
  Dockerfile
  README.md
  requirements.in
  requirements.txt
Labels: bug
