Repository ansible-community/toolset, pull requests merged in 2021-02, with the labels that each got.

#95 Assure ruamel clib is installed
  requirements.in
Labels: bug

#101 Update requirements.in
  requirements.in
Labels: skip-changelog

#96 Bump dependencies
  .github/dependabot.yml
  requirements.txt
  tox.ini
Labels: enhancement

#100 Multi-stage build to reduce image size
  Dockerfile
Labels: enhancement

#108 Use sudo to avoid skopeo login failure
  .github/workflows/mirror.yml
Labels: bug

#109 Updated deps
  requirements.txt
Labels: dependencies
